	<!--[if !IE]> -->
	<script type="text/javascript" src="<%=staticFilesRoot%>js/resizetaOverlay.js" defer="defer"></script>
	<!-- <![endif]-->
	<script type="text/javascript" src="<%=staticFilesRoot%>js/getElementsBySelector.js"></script>
	<script type="text/javascript" src="<%=staticFilesRoot%>js/behavior.js"></script>
	<script type="text/javascript" src="<%=staticFilesRoot%>js/MessAdmin.js"></script><%-- Can not be defered as some of its functions are used in pages... --%>